# Production application config (api.appConfigPath: files/prod-application.yaml)

api:
  server:
    readHeaderTimeoutSeconds: 5
    readTimeoutSeconds: 30
    writeTimeoutSeconds: 30
    idleTimeoutSeconds: 60
    shutdownTimeoutSeconds: 15
  request:
    requestTimeoutSeconds: 30
  readyz:
    pingTimeoutSeconds: 2
  databaseRetry:
    maxAttempts: 6
    retryBackoffSeconds: 2
