{{- if and .Values.api.externalSecret .Values.api.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "config-manager.apiSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "config-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  refreshInterval: {{ .Values.api.externalSecret.refreshInterval | default "30s" | quote }}
  secretStoreRef:
    name: {{ required "api.externalSecret.clusterSecretStore.name is required" .Values.api.externalSecret.clusterSecretStore.name | quote }}
    kind: {{ .Values.api.externalSecret.clusterSecretStore.kind | default "ClusterSecretStore" | quote }}
  target:
    name: {{ include "config-manager.apiSecretName" . }}
  dataFrom:
    - extract:
        key: {{ required "api.externalSecret.vaultPath is required" .Values.api.externalSecret.vaultPath | quote }}
{{- end }}

