{{- if and (not .Values.database.existingSecretName) .Values.database.url -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "config-manager.fullname" . }}-db
  labels:
    {{- include "config-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | quote }}
{{- end -}}

