apiVersion: v1
kind: Service
metadata:
  name: {{ include "config-manager.fullname" . }}-ui
  labels:
    {{- include "config-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type | default "ClusterIP" }}
  selector:
    {{- include "config-manager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
  ports:
    - name: http
      port: {{ .Values.ui.service.port }}
      targetPort: http

